// Auto-generated by svg-sprite-webpack-loader
// Do not edit this file manually

/**
 * Enum containing all available icon IDs
 */
export enum IconId {
  IconUser = "icon-user",
  IconSettings = "icon-settings",
  IconHome = "icon-home",
  IconSocialGoogle = "icon-social-google",
  IconSocialGithub = "icon-social-github",
  IconNavigationMenu = "icon-navigation-menu",
}

/**
 * Union type of all available icon IDs
 */
export type IconIdType = 
  | "icon-user"
  | "icon-settings"
  | "icon-home"
  | "icon-social-google"
  | "icon-social-github"
  | "icon-navigation-menu";

/**
 * Props for icon components
 */
export interface IconProps {
  id: IconId | IconIdType;
  className?: string;
  size?: number | string;
}

/**
 * Array of all available icon IDs
 */
export const ALL_ICON_IDS = [
  "icon-user",
  "icon-settings",
  "icon-home",
  "icon-social-google",
  "icon-social-github",
  "icon-navigation-menu"
] as const;

/**
 * Type guard to check if a string is a valid icon ID
 */
export function isValidIconId(id: string): id is IconId | IconIdType {
  return ALL_ICON_IDS.includes(id as any);
}
