import * as fs from "fs";
import * as path from "path";

/**
 * Options for Icon component generation
 */
export interface IconComponentGenerationOptions {
  /**
   * Output path for the Icon component file
   * Can be relative or absolute path
   */
  outputFile: string;

  /**
   * Path to the generated types file (for import statement)
   * Relative to the component output file
   */
  typesFileRelativePath: string;

  /**
   * Whether to log output messages
   * @default true
   */
  verbose?: boolean;
}

/**
 * Generate React Icon component file
 */
export function generateReactIconComponent(
  options: IconComponentGenerationOptions
): void {
  const { outputFile, typesFileRelativePath, verbose = true } = options;

  try {
    const projectRoot = process.cwd();
    const absoluteOutputFile = path.resolve(projectRoot, outputFile);

    // Normalize the import path (ensure it uses / separator and doesn't start with ./ if in same dir)
    const normalizedImportPath = typesFileRelativePath
      .replace(/\\/g, "/")
      .replace(/\.tsx?$/, "");

    const content = `// Auto-generated by typed-svg-sprite
// Do not edit this file manually

import type { IconHref } from "${normalizedImportPath}";

export interface IconProps extends React.ComponentPropsWithRef<"svg"> {
  /** The icon href (import from generated/icons.ts) */
  href: IconHref;
  /** Size shorthand for width and height */
  size?: number | string;
}

export function Icon({
  href,
  size = 24,
  width,
  height,
  className = "",
  viewBox = "0 0 24 24",
  fill = "currentColor",
  ...props
}: IconProps) {
  return (
    <svg
      className={className}
      width={width || size}
      height={height || size}
      viewBox={viewBox}
      fill={fill}
      aria-hidden="true"
      {...props}
    >
      <use href={href} />
    </svg>
  );
}
`;

    // Write component file
    const outputDir = path.dirname(absoluteOutputFile);
    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(absoluteOutputFile, content, "utf8");

    if (verbose) {
      console.log(`[svg-sprite] ✅ Generated React Icon component → ${outputFile}`);
    }
  } catch (error) {
    if (verbose) {
      console.error("[svg-sprite] Error generating React Icon component:", error);
    }
    throw error;
  }
}

/**
 * Generate Astro Icon component file
 */
export function generateAstroIconComponent(
  options: IconComponentGenerationOptions
): void {
  const { outputFile, typesFileRelativePath, verbose = true } = options;

  try {
    const projectRoot = process.cwd();
    const absoluteOutputFile = path.resolve(projectRoot, outputFile);

    // Normalize the import path (ensure it uses / separator)
    const normalizedImportPath = typesFileRelativePath
      .replace(/\\/g, "/")
      .replace(/\.tsx?$/, "");

    const content = `---
// Auto-generated by typed-svg-sprite
// Do not edit this file manually

import type { IconHref } from "${normalizedImportPath}";

export interface Props {
  /** The icon href (import from generated/icons.ts) */
  href: IconHref;
  /** Size shorthand for width and height */
  size?: number | string;
  /** CSS class */
  class?: string;
  /** viewBox attribute */
  viewBox?: string;
  /** fill attribute */
  fill?: string;
  /** Additional HTML attributes */
  [key: string]: any;
}

const {
  href,
  size = 24,
  class: className = "",
  viewBox = "0 0 24 24",
  fill = "currentColor",
  ...props
} = Astro.props;

const width = props.width || size;
const height = props.height || size;
---

<svg
  class={className}
  width={width}
  height={height}
  viewBox={viewBox}
  fill={fill}
  aria-hidden="true"
  {...props}
>
  <use href={href} />
</svg>
`;

    // Write component file
    const outputDir = path.dirname(absoluteOutputFile);
    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(absoluteOutputFile, content, "utf8");

    if (verbose) {
      console.log(`[svg-sprite] ✅ Generated Astro Icon component → ${outputFile}`);
    }
  } catch (error) {
    if (verbose) {
      console.error("[svg-sprite] Error generating Astro Icon component:", error);
    }
    throw error;
  }
}