import * as fs from "fs";
import * as path from "path";
import type { SvgSymbol } from "./core.js";

/**
 * Options for TypeScript types generation
 */
export interface TypesGenerationOptions {
  /**
   * Symbols to generate types for
   */
  symbols: SvgSymbol[];

  /**
   * URL path where the sprite file will be served from
   * @example "/"
   */
  spriteUrl: string;

  /**
   * Filename of the sprite file
   * @example "sprite.svg"
   */
  spriteFilename: string;

  /**
   * Output path for the TypeScript types file
   * Can be relative or absolute path
   */
  outputFile: string;

  /**
   * Whether to log output messages
   * @default true
   */
  verbose?: boolean;
}

/**
 * Generate TypeScript types file from SVG symbols
 */
export function generateTypesFile(options: TypesGenerationOptions): void {
  const {
    symbols,
    spriteUrl,
    spriteFilename,
    outputFile,
    verbose = true,
  } = options;

  try {
    const projectRoot = process.cwd();
    const absoluteOutputFile = path.resolve(projectRoot, outputFile);
    const spriteUrlWithFilename = spriteUrl.endsWith("/")
      ? `${spriteUrl}${spriteFilename}`
      : `${spriteUrl}/${spriteFilename}`;

    // Generate TypeScript content
    const iconIds = symbols.map((s) => s.id);
    const iconIdType = iconIds.map((id) => `  | "${id}"`).join("\n");
    const iconExports = symbols
      .map((s) => {
        // Convert kebab-case to UPPER_SNAKE_CASE
        const constantName = s.id.replace(/-/g, "_").toUpperCase();
        return `export const ${constantName}: IconHref = "${spriteUrlWithFilename}#${s.id}";`;
      })
      .join("\n");

    const content = `// Auto-generated by svg-sprite-loader
// Do not edit this file manually

/**
 * Available icon IDs in the sprite
 */
export type IconId =
${iconIdType};

/**
 * Type-safe icon href (sprite URL + fragment identifier)
 */
export type IconHref = \`${spriteUrlWithFilename}#\${IconId}\`;

/**
 * Get the full sprite URL for an icon ID
 */
export function getIconHref(iconId: IconId): IconHref {
  return \`${spriteUrlWithFilename}#\${iconId}\` as IconHref;
}

/**
 * Pre-built icon references
 */
${iconExports}

/**
 * All available icons as an array
 */
export const allIcons: IconId[] = [
${iconIds.map((id) => `  "${id}",`).join("\n")}
];
`;

    // Write types file
    const outputDir = path.dirname(absoluteOutputFile);
    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(absoluteOutputFile, content, "utf8");

    if (verbose) {
      console.log(`[svg-sprite] ✅ Generated types file → ${outputFile}`);
    }
  } catch (error) {
    if (verbose) {
      console.error("[svg-sprite] Error generating types file:", error);
    }
    throw error;
  }
}
